# Generated by Django 5.2.1 on 2025-05-26 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_alter_caseupdate_options_and_more'),
        ('user', '0003_missingperson_found_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseevidence',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='caseevidence',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='title',
            field=models.CharField(default='Untitled Evidence', max_length=200),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='user.missingperson'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.missingperson')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
