# Generated by Django 5.2.1 on 2025-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_alter_caseevidence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseevidence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Missing Person Evidence', 'verbose_name_plural': 'Missing Person Evidence'},
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'Photograph'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='photo', max_length=20),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='description',
            field=models.TextField(default='Evidence related to missing person case'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='file',
            field=models.FileField(upload_to='missing_person_evidence/'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='title',
            field=models.CharField(default='Missing Person Evidence', max_length=200),
        ),
    ]
