# Generated by Django 5.2.1 on 2025-05-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_alter_caseevidence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseupdate',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='caseupdate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='progress',
            field=models.CharField(choices=[('0', '0%'), ('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
