# Generated by Django 5.2.1 on 2025-05-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='frontend_user',
        ),
    ]
