# Generated by Django 5.2.1 on 2025-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, help_text='Format: 12345-1234567-1', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('IGP', 'Inspector General of Police (IGP)'), ('DIG', 'Deputy Inspector General (DIG)'), ('SSP', 'Senior Superintendent of Police (SSP)'), ('SP', 'Superintendent of Police (SP)'), ('DSP', 'Deputy Superintendent of Police (DSP)'), ('ASP', 'Assistant Superintendent of Police (ASP)'), ('Inspector', 'Inspector'), ('SI', 'Sub-Inspector (SI)'), ('ASI', 'Assistant Sub-Inspector (ASI)'), ('HC', 'Head Constable (HC)'), ('Constable', 'Constable')], max_length=20, null=True),
        ),
    ]
