# Generated by Django 5.2.1 on 2025-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_user_cnic_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cases_closed',
            field=models.PositiveIntegerField(default=0, help_text='Number of cases closed by this officer'),
        ),
    ]
