# Generated by Django 5.2.1 on 2025-05-25 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('height', models.CharField(help_text='Height in feet and inches', max_length=50)),
                ('weight', models.CharField(help_text='Weight in kg', max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('distinguishing_marks', models.TextField(blank=True, help_text='Scars, tattoos, or other identifying marks')),
                ('last_seen_date', models.DateField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_wearing', models.TextField(help_text='Description of clothes last seen wearing')),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_contact', models.CharField(blank=True, max_length=15)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('found', 'Found'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('description', models.TextField(help_text='Additional details about the missing person')),
                ('photo', models.ImageField(upload_to='missing_persons/')),
                ('additional_photos', models.ImageField(blank=True, null=True, upload_to='missing_persons/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_missing_persons', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_missing_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-created_at'],
            },
        ),
    ]
