# Generated by Django 5.2.1 on 2025-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_caseupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='location_found',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('investigation', 'Under Investigation'), ('found', 'Found'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
