# Generated by Django 5.2.1 on 2025-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20250610_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='closure_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_persons/closure_proofs/'),
        ),
    ]
