# Generated by Django 5.2.1 on 2025-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_missingperson_closure_proof_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='skin_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight in kg', max_length=50),
        ),
    ]
