# Generated by Django 5.2.4 on 2025-07-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_feedback_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='assigned_officer',
        ),
    ]
